#pragma once

namespace coquic::quic::test {

void connection_set_force_missing_packet_metadata_for_tests(bool enabled);
void connection_set_force_missing_fallback_packet_length_for_tests(bool enabled);
void connection_set_force_appended_fragment_base_datagram_failure_for_tests(bool enabled);
void connection_set_force_aead_confidentiality_limit_for_tests(bool enabled);
void connection_set_force_aead_integrity_limit_for_tests(bool enabled);
void connection_set_force_application_candidate_estimate_failure_countdown_for_tests(int value);
void connection_set_force_candidate_datagram_serialization_failure_countdown_for_tests(int value);

} // namespace coquic::quic::test
