name: Format / Lint

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Format Check
        run: nix develop -c pre-commit run clang-format --all-files --show-diff-on-failure

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Refresh compile_commands.json
        run: nix develop -c ./scripts/refresh-compile-commands.sh

      - name: Lint
        run: nix develop -c pre-commit run coquic-clang-tidy --all-files --show-diff-on-failure
