from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = Path(__file__).with_name("public-monitor-v3.json")
OUTPUT_PATH = ROOT / "site" / "next" / "src" / "generated" / "steward-public.ts"
PYTHON_OUTPUT_PATH = ROOT / "steward" / "src" / "coquic_steward" / "public_schema.py"


def schema_version(schema: dict[str, Any]) -> int:
    version = schema.get("properties", {}).get("schema_version", {}).get("const")
    if type(version) is not int or version < 1:
        raise ValueError("schema_version must have a positive integer const")
    return version


def render_types(schema: dict[str, Any]) -> str:
    definitions = schema.get("$defs", {})
    version = schema_version(schema)
    lines = [
        "/* eslint-disable */",
        "// Generated by steward/schema/generate_types.py. Do not edit manually.",
        "",
        f"export const PUBLIC_STEWARD_SCHEMA_VERSION = {version};",
        "",
    ]
    for name in sorted(definitions):
        lines.extend(_render_alias(_type_name(name), definitions[name], schema))
        lines.append("")
    lines.extend(_render_alias("PublicStewardMonitor", schema, schema))
    return "\n".join(lines).rstrip() + "\n"


def render_python_contract(schema: dict[str, Any]) -> str:
    version = schema_version(schema)
    return (
        '"""Generated by steward/schema/generate_types.py. Do not edit manually."""\n\n'
        f"PUBLIC_STEWARD_SCHEMA_VERSION = {version}\n"
    )


def _render_alias(name: str, schema: dict[str, Any], root: dict[str, Any]) -> list[str]:
    return [f"export type {name} = {_ts_type(schema, root, inline=True)};"]


def _ts_type(schema: dict[str, Any], root: dict[str, Any], *, inline: bool = False) -> str:
    if "$ref" in schema:
        return _type_name(str(schema["$ref"]).rsplit("/", 1)[-1])
    if "const" in schema:
        return _literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_literal(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(_ts_type(item, root) for item in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(_ts_type(item, root) for item in schema["oneOf"])
    expected = schema.get("type")
    if isinstance(expected, list):
        types = []
        for item in expected:
            if item in {"object", "array"}:
                types.append(_ts_type({**schema, "type": item}, root))
            else:
                types.append(_primitive_type(item))
        return " | ".join(types)
    if expected == "object":
        properties = schema.get("properties", {})
        if not properties:
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        fields = []
        for key, child in properties.items():
            optional = "" if key in required else "?"
            fields.append(f"{key}{optional}: {_ts_type(child, root)}")
        return "{ " + "; ".join(fields) + " }"
    if expected == "array":
        return f"Array<{_ts_type(schema.get('items', {}), root)}>"
    return _primitive_type(expected)


def _primitive_type(value: object) -> str:
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null", "object": "Record<string, unknown>", "array": "unknown[]"}.get(value, "unknown")


def _type_name(value: str) -> str:
    parts = re.findall(r"[A-Za-z0-9]+", value)
    return "Public" + "".join(part[:1].upper() + part[1:] for part in parts)


def _literal(value: object) -> str:
    return json.dumps(value, separators=(",", ":"))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--schema", type=Path, default=SCHEMA_PATH)
    parser.add_argument("--typescript-output", type=Path, default=OUTPUT_PATH)
    parser.add_argument("--python-output", type=Path, default=PYTHON_OUTPUT_PATH)
    args = parser.parse_args()
    schema_path = args.schema
    output_path = args.typescript_output
    python_output_path = args.python_output
    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    rendered = {
        output_path: render_types(schema),
        python_output_path: render_python_contract(schema),
    }
    if args.check:
        stale = [
            str(path)
            for path, expected in rendered.items()
            if not path.exists() or path.read_text(encoding="utf-8") != expected
        ]
        if stale:
            print("generated output is stale:")
            print("\n".join(stale))
            return 1
        return 0
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
