from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = Path(__file__).with_name("public-monitor-v3.json")
OUTPUT_PATH = ROOT / "site" / "next" / "src" / "generated" / "steward-public.ts"


def render_types(schema: dict[str, Any]) -> str:
    definitions = schema.get("$defs", {})
    lines = [
        "/* eslint-disable */",
        "// Generated by steward/schema/generate_types.py. Do not edit manually.",
        "",
    ]
    for name in sorted(definitions):
        lines.extend(_render_alias(_type_name(name), definitions[name], schema))
        lines.append("")
    lines.extend(_render_alias("PublicStewardMonitor", schema, schema))
    return "\n".join(lines).rstrip() + "\n"


def _render_alias(name: str, schema: dict[str, Any], root: dict[str, Any]) -> list[str]:
    return [f"export type {name} = {_ts_type(schema, root, inline=True)};"]


def _ts_type(schema: dict[str, Any], root: dict[str, Any], *, inline: bool = False) -> str:
    if "$ref" in schema:
        return _type_name(str(schema["$ref"]).rsplit("/", 1)[-1])
    if "const" in schema:
        return _literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_literal(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(_ts_type(item, root) for item in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(_ts_type(item, root) for item in schema["oneOf"])
    expected = schema.get("type")
    if isinstance(expected, list):
        types = []
        for item in expected:
            if item in {"object", "array"}:
                types.append(_ts_type({**schema, "type": item}, root))
            else:
                types.append(_primitive_type(item))
        return " | ".join(types)
    if expected == "object":
        properties = schema.get("properties", {})
        if not properties:
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        fields = []
        for key, child in properties.items():
            optional = "" if key in required else "?"
            fields.append(f"{key}{optional}: {_ts_type(child, root)}")
        return "{ " + "; ".join(fields) + " }"
    if expected == "array":
        return f"Array<{_ts_type(schema.get('items', {}), root)}>"
    return _primitive_type(expected)


def _primitive_type(value: object) -> str:
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null", "object": "Record<string, unknown>", "array": "unknown[]"}.get(value, "unknown")


def _type_name(value: str) -> str:
    parts = re.findall(r"[A-Za-z0-9]+", value)
    return "Public" + "".join(part[:1].upper() + part[1:] for part in parts)


def _literal(value: object) -> str:
    return json.dumps(value, separators=(",", ":"))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_types(json.loads(SCHEMA_PATH.read_text(encoding="utf-8")))
    current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else None
    if args.check:
        if current != rendered:
            print(f"generated output is stale: {OUTPUT_PATH}")
            return 1
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
